server:
  port: 8080

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    try-it-out-enabled: true
  api-docs:
    path: /v3/api-docs

logging:
  level:
    com.cryptotax: DEBUG
